#!/usr/bin/env bash
# This is my bash script
bestschool=0
while [ $bestschool -ne 10 ]; do
    printf "Best School\n"
if [[ "$bestschool" -eq 8 ]]; then
    printf "Hi\n"
fi
    ((bestschool++));

done;
