#!/usr/bin/env bash
# This is my bash script
bestschool=0
while [ $bestschool -ne 10 ]; do
    if [[ "bestschool" -eq 3 ]]; then
        printf "bad luck\n"
    elif [[ "$bestschool" -eq 7 ]]; then
    else
       printf "good luck\n"
    fi
    ((bestschool++))
done;    
